In [27]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


In [22]:
# labelled_emails_df = pd.read_csv('../data/04_encoded_labelled_emails.csv')
# labelled_emails_df.sample(10, random_state=12)

In [23]:
Y_train = np.load('../model_data/Y_train.npy')
Y_test = np.load('../model_data/Y_test.npy')

print('Y_train: ', Y_train)
print('Y_test: ', Y_test)
print('shape: ', Y_train.shape, Y_test.shape)

X_train = np.load("../model_data/X_train_bert.npy")
X_test = np.load("../model_data/X_test_bert.npy")

print('X_train: ', X_train)
print('X_test: ', X_test)
print('shape: ', X_train.shape, X_test.shape)

Y_train:  [[1 1 0 0]
 [0 1 1 0]
 [1 0 0 1]
 ...
 [1 1 0 0]
 [0 0 0 1]
 [1 0 1 0]]
Y_test:  [[1 0 0 1]
 [1 0 1 0]
 [0 0 1 1]
 ...
 [0 1 1 0]
 [1 0 0 0]
 [1 1 0 0]]
shape:  (2088, 4) (523, 4)
X_train:  [[-0.6314712  -0.52617776 -0.94768167 ... -0.5904847  -0.6615315
   0.77338326]
 [-0.7271016  -0.50922173 -0.966358   ... -0.8682175  -0.58734834
   0.53512746]
 [-0.6152391  -0.5291411  -0.97700727 ... -0.9766525  -0.6205291
   0.55183804]
 ...
 [-0.564998   -0.42946798 -0.92218417 ... -0.7160475  -0.611352
   0.61186284]
 [-0.77536887 -0.4544915  -0.96167237 ... -0.9183127  -0.4488551
   0.38754222]
 [-0.47860402 -0.5482809  -0.9917552  ... -0.96489906 -0.63556933
   0.18608356]]
X_test:  [[-0.28295514 -0.25646207 -0.9408917  ... -0.86757624 -0.4368691
   0.29567564]
 [-0.17603873 -0.02102108  0.3163479  ...  0.04302573 -0.2302131
   0.31858164]
 [-0.6733913  -0.3732347  -0.5620626  ... -0.6899617  -0.67061347
   0.6852762 ]
 ...
 [ 0.00404818 -0.49441555 -0.9444312  ... -0.7161667  -0.4

## Train a Logistic Regression classifier

In [26]:
log_reg = OneVsRestClassifier(LogisticRegression(max_iter=1000))
log_reg.fit(X_train, Y_train)
y_pred_log_reg = log_reg.predict(X_test)
y_pred_log_reg

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       ...,
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])